#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.config.grafana.name }}
  namespace: {{ $.Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: ia-grafana
  ports:
  - name: grafana-port
    port: {{ $.Values.config.grafana.grafana_port }}
  
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels:
    app: ia-grafana
  name: deployment-grafana
  namespace: {{ $.Values.namespace }}

spec:
  selector:
    matchLabels:
      app: ia-grafana
  template:
    metadata:
      labels:
        app: ia-grafana
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ $.Values.env.TIMESERIES_UID }}
        runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
        fsGroup: {{ $.Values.env.TIMESERIES_UID }}
        seccompProfile:
          type: RuntimeDefault
      {{- if and $.Values.DOCKER_USERNAME $.Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      containers:
      - name: ia-grafana
        image: grafana/grafana-oss:12.0.0-ubuntu
        imagePullPolicy: {{ $.Values.imagePullPolicy }}
        securityContext:
          runAsUser: {{ $.Values.env.TIMESERIES_UID }}
          runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: vol-temp-grafana
          mountPath: /tmp
        - name: vol-grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-dashboard-json
          mountPath: /etc/grafana/provisioning/dashboards/grafana-dashboard.json
          subPath: grafana-dashboard.json
        - name: grafana-dashboard-yml
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
          subPath: dashboards.yml
        - name: grafana-datasource
          mountPath: /etc/grafana/provisioning/datasources/datasources.yml
          subPath: datasources.yml
        env:
        - name: GF_SERVER_PROTOCOL
          value: "http"
        - name: INFLUXDB_USERNAME
          value: '{{ $.Values.env.INFLUXDB_USERNAME }}'
        - name: INFLUXDB_PASSWORD
          value: '{{ $.Values.env.INFLUXDB_PASSWORD }}'
        - name: INFLUX_SERVER
          value: "influxdb"
        - name: GRAFANA_SERVER
          value: "0.0.0.0"
        - name: GF_SECURITY_ADMIN_USER
          value: '{{ $.Values.env.VISUALIZER_GRAFANA_USER }}'
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: '{{ $.Values.env.VISUALIZER_GRAFANA_PASSWORD }}'
        - name: GF_PROVISIONING_ENABLE
          value: "true"
        - name: INFLUXDB_DB
          value: "datain"
        - name: GF_PROVISIONING_DASHBOARDS
          value: "/etc/grafana/provisioning/dashboards"
        - name: GF_LOG_LEVEL
          value: '{{ $.Values.env.LOG_LEVEL }}'
        - name: GF_AUTH_LOGIN_MAXIMUM_INACTIVE_LIFETIME_DURATION
          value: '{{ $.Values.env.VISUALIZER_GRAFANA_INACTIVE_TIMEOUT }}'
        - name: GF_AUTH_LOGIN_MAXIMUM_LIFETIME_DURATION
          value: '{{ $.Values.env.VISUALIZER_GRAFANA_INACTIVE_TIMEOUT }}'
        - name: GF_SECURITY_LOGIN_REMEMBER_DAYS
          value: "1"
      volumes:
      - name: vol-temp-grafana
        emptyDir: {}
      - name: vol-grafana-data
        emptyDir: {}
      - name: grafana-dashboard-json
        configMap:
          name: grafana-dashboard-json
      - name: grafana-datasource
        configMap:
          name: grafana-datasource
      - name: grafana-dashboard-yml
        configMap:
          name: grafana-dashboard-yml
          
