#
# Apache v2 license
# Copyright (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.config.time_series_analytics_microservice.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.config.time_series_analytics_microservice.kapacitor_port }}
    name: kapacitor-port
  - name: rest-api-port
    port: {{ .Values.config.time_series_analytics_microservice_rest_api.rest_api_port }}
  selector:
    app: ia-time-series-analytics-microservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ia-time-series-analytics-microservice
  name: deployment-time-series-analytics-microservice
  namespace: {{ .Values.namespace }}

spec:
  selector:
    matchLabels:
      app: ia-time-series-analytics-microservice
  template:
    metadata:
      labels:
        app: ia-time-series-analytics-microservice
    spec:
      {{- if and .Values.DOCKER_USERNAME .Values.DOCKER_PASSWORD }}
      imagePullSecrets:
      - name: registryauth
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ $.Values.env.TIMESERIES_UID }}
        runAsGroup: {{ $.Values.env.TIMESERIES_UID }}
        fsGroup: {{ $.Values.env.TIMESERIES_UID }}
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: [109,110,992]  # render group IDs for ubuntu 20.04, 22.04 and 24.04 host OS
      containers:
      - name: ia-time-series-analytics-microservice
        image: {{ .Values.DOCKER_REGISTRY }}{{ .Values.images.time_series_analytics_image }}{{ if .Values.images.image_suffix }}-{{ .Values.images.image_suffix }}{{ end }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        securityContext:
          {{- if .Values.privileged_access_required }}
          privileged: true # Required for /dev/dri access, if using GPU devices
          allowPrivilegeEscalation: true
          {{- else }}
          privileged: false
          allowPrivilegeEscalation: false
          {{- end }}
          runAsNonRoot: true
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: vol-temp-time-series-analytics-microservice
          mountPath: /tmp
        - name: time-series-analytics-microservice-config
          mountPath: /app/config.json
          subPath: config.json
        - name: dev-dri
          mountPath: /dev/dri
          readOnly: true # Reduce risk while preserving access to GPU/NPU devices
        - name: run-udev
          mountPath: /run/udev
          readOnly: true # Reduce risk while preserving access to udev information

        env:
        - name: HTTP_PROXY
          value: '{{ .Values.env.HTTP_PROXY }}'
        - name: HTTPS_PROXY
          value: '{{ .Values.env.HTTPS_PROXY }}'
        - name: NO_PROXY
          value: "influxdb,ia-time-series-analytics-microservice,ia-mqtt-broker,ia-opcua-server,localhost,model-registry"
        - name: TIMESERIES_NO_PROXY
          value: '{{ .Values.env.TIMESERIES_NO_PROXY }}'
        - name: PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION
          value: python
        - name: KAPACITOR_INFLUXDB_0_USERNAME
          value: '{{ .Values.env.INFLUXDB_USERNAME }}'
        - name: KAPACITOR_PORT
          value: '{{ .Values.config.time_series_analytics_microservice.kapacitor_port }}'
        - name: KAPACITOR_INFLUXDB_0_PASSWORD
          value: '{{ .Values.env.INFLUXDB_PASSWORD }}'
        - name: KAPACITOR_URL
          value: "http://ia-time-series-analytics-microservice:{{ .Values.config.time_series_analytics_microservice.kapacitor_port }}/"
        - name: KAPACITOR_UNSAFE_SSL
          value: "true"
        - name: KAPACITOR_INFLUXDB_0_URLS_0
          value: "http://influxdb:{{ .Values.config.influx_db_server.influx_http }}/"
        - name: INFLUX_SERVER
          value: "influxdb"
        - name: INFLUXDB_PORT
          value: "8086"
        - name: INFLUXDB_DBNAME
          value: "datain"
        - name: KAPACITOR_LOGGING_LEVEL
          value: '{{ .Values.env.LOG_LEVEL }}'
        - name: MQTT_BROKER_HOST
          value: "ia-mqtt-broker" 
        - name: MQTT_BROKER_PORT
          value: "1883" 
        - name: MODEL_REGISTRY_URL
          value: "http://model-registry:8111"
        - name: SAMPLE_APP
          value: '{{ .Values.env.SAMPLE_APP }}'
        - name: REST_API_ROOT_PATH
          value: "/ts-api"
      volumes:
      - name: vol-temp-time-series-analytics-microservice
        emptyDir: {}
      - name: time-series-analytics-microservice-config
        configMap:
          name: time-series-analytics-microservice-config
      - name: dev-dri
        hostPath:
          path: /dev/dri
      - name: run-udev
        hostPath:
          path: /run/udev