---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nvr-event-router-ui-nginx-config
data:
  default.conf: |
    server {
      listen 80;
      server_name _;

      location / {
        proxy_pass http://nvr-event-router-ui:7860;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvr-event-router-ui-nginx
  labels:
    app: nvr-event-router-ui-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nvr-event-router-ui-nginx
  template:
    metadata:
      labels:
        app: nvr-event-router-ui-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginx-config-volume
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nvr-event-router-ui-nginx-config
---
{{- $svc := default (dict) .Values.ingress.service }}
apiVersion: v1
kind: Service
metadata:
  name: nvr-event-router-ui-nginx
spec:
  type: {{ default "NodePort" $svc.type }}
  selector:
    app: nvr-event-router-ui-nginx
  ports:
    - protocol: TCP
      port: {{ default 80 $svc.port }}
      targetPort: {{ default 80 $svc.targetPort }}
      {{- if and (eq (default "NodePort" $svc.type) "NodePort") $svc.nodePort }}
      nodePort: {{ $svc.nodePort }}
      {{- end }}
